export const WEBFLOW_BUTTON_SELECTORS = [
  '.w-button',
  'a.w-button',
  '.button', // Common user class
  '[class*="button"]', // Catch-all for user classes
  '.w-form-submit',
];

export const WEBFLOW_NAV_SELECTORS = [
  '.w-nav',
  '.w-nav-menu',
  '.w-nav-link',
  '.w-dropdown',
  '.w-dropdown-toggle',
  '.w-dropdown-list',
  '.navbar', // Common user class
];

export const WEBFLOW_HEADING_SELECTORS = [
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6', // Webflow rarely uses classes for semantics unless styled
  '.heading-1',
  '.heading-2', // Common user classes generated by Webflow
  '.w-heading', // Check if this exists in your target sites, sometimes absent
];

export const WEBFLOW_PARAGRAPH_SELECTORS = [
  'p',
  '.w-richtext p',
  '.paragraph', // Common user class
  '.w-paragraph',
];

export const WEBFLOW_IMAGE_SELECTORS = [
  'img.w-inline-block',
  '.w-richtext figure img',
  '.w-lightbox-image',
  '.w-background-image', // Divs acting as images
];

export const WEBFLOW_LINK_SELECTORS = [
  'a.w-inline-block',
  '.w-richtext a',
  '.link', // Common user class
];

export const WEBFLOW_SECTION_SELECTORS = [
  '.w-section',
  '.section', // Common user class
  '.w-container',
  '.container', // Common user class
  '.w-row',
];

export const WEBFLOW_BLOCK_SELECTORS = ['.w-col', '.w-layout-grid', '.w-dyn-list', '.w-dyn-item'];

export const WEBFLOW_DATA_ATTRIBUTES = [
  'data-wf-domain',
  'data-wf-page',
  'data-wf-site',
  'data-w-id', // Interaction ID
  'data-ix', // Legacy interaction ID
];

export const WEBFLOW_UNSTABLE_ID_PATTERNS = [
  // Webflow IDs are usually user-generated stable IDs, but some generated ones exist
  /^w-node-/, // Grid/Flex auto-generated IDs
];

// Helper to determine if an element is a Webflow element
export const isWebflowElement = (element: Element): boolean => {
  if (!element) return false;

  if (element.className && typeof element.className === 'string') {
    if (element.className.includes('w-')) return true;
  }

  // Check for auto-generated IDs
  if (element.id && element.id.startsWith('w-node-')) return true;

  // Check interaction attributes
  if (element.getAttribute('data-w-id')) return true;

  return false;
};
